onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /system_tb/CLK
add wave -noupdate /system_tb/nRST
add wave -noupdate -divider CPU0
add wave -noupdate -group PC0 /system_tb/DUT/CPU/DP0/pcif/pc
add wave -noupdate -group PC0 /system_tb/DUT/CPU/DP0/pcif/next_pc
add wave -noupdate -group PC0 /system_tb/DUT/CPU/DP0/pcif/pc_comb
add wave -noupdate -group PC0 /system_tb/DUT/CPU/DP0/pcif/pc_incr
add wave -noupdate -group CIF0 /system_tb/DUT/CPU/cif0/iwait
add wave -noupdate -group CIF0 /system_tb/DUT/CPU/cif0/dwait
add wave -noupdate -group CIF0 /system_tb/DUT/CPU/cif0/iREN
add wave -noupdate -group CIF0 /system_tb/DUT/CPU/cif0/dREN
add wave -noupdate -group CIF0 /system_tb/DUT/CPU/cif0/dWEN
add wave -noupdate -group CIF0 /system_tb/DUT/CPU/cif0/iload
add wave -noupdate -group CIF0 /system_tb/DUT/CPU/cif0/dload
add wave -noupdate -group CIF0 /system_tb/DUT/CPU/cif0/dstore
add wave -noupdate -group CIF0 /system_tb/DUT/CPU/cif0/iaddr
add wave -noupdate -group CIF0 /system_tb/DUT/CPU/cif0/daddr
add wave -noupdate -group CIF0 /system_tb/DUT/CPU/cif0/ccwait
add wave -noupdate -group CIF0 /system_tb/DUT/CPU/cif0/ccinv
add wave -noupdate -group CIF0 /system_tb/DUT/CPU/cif0/ccwrite
add wave -noupdate -group CIF0 /system_tb/DUT/CPU/cif0/cctrans
add wave -noupdate -group CIF0 /system_tb/DUT/CPU/cif0/ccsnoopaddr
add wave -noupdate -group CIF0 /system_tb/DUT/CPU/cif0/ccflushed
add wave -noupdate -group dcache0 /system_tb/DUT/CPU/CM0/DCACHE/currState
add wave -noupdate -group dcache0 /system_tb/DUT/CPU/CM0/DCACHE/nextState
add wave -noupdate -group dcache0 /system_tb/DUT/CPU/CM0/DCACHE/CLK
add wave -noupdate -group dcache0 /system_tb/DUT/CPU/CM0/DCACHE/nRST
add wave -noupdate -group dcache0 /system_tb/DUT/CPU/CM0/DCACHE/index
add wave -noupdate -group dcache0 /system_tb/DUT/CPU/CM0/DCACHE/addrTag
add wave -noupdate -group dcache0 /system_tb/DUT/CPU/CM0/DCACHE/addrIndex
add wave -noupdate -group dcache0 /system_tb/DUT/CPU/CM0/DCACHE/addrOffset
add wave -noupdate -group dcache0 /system_tb/DUT/CPU/CM0/DCACHE/snoopTag
add wave -noupdate -group dcache0 /system_tb/DUT/CPU/CM0/DCACHE/snoopIndex
add wave -noupdate -group dcache0 /system_tb/DUT/CPU/CM0/DCACHE/snoopOffset
add wave -noupdate -group dcache0 /system_tb/DUT/CPU/CM0/DCACHE/next_flush_set
add wave -noupdate -group dcache0 /system_tb/DUT/CPU/CM0/DCACHE/flush_set
add wave -noupdate -group dcache0 /system_tb/DUT/CPU/CM0/DCACHE/next_flush_frame
add wave -noupdate -group dcache0 /system_tb/DUT/CPU/CM0/DCACHE/flush_frame
add wave -noupdate -group dcache0 /system_tb/DUT/CPU/CM0/DCACHE/snoopFrame
add wave -noupdate -group dcache0 /system_tb/DUT/CPU/CM0/DCACHE/nextSnoopFrame
add wave -noupdate -group dcache0 /system_tb/DUT/CPU/CM0/DCACHE/cnt
add wave -noupdate -group dcache0 /system_tb/DUT/CPU/CM0/DCACHE/next_cnt
add wave -noupdate -group dcache0 /system_tb/DUT/CPU/CM0/DCACHE/i
add wave -noupdate -group dcache0 /system_tb/DUT/CPU/CM0/DCACHE/j
add wave -noupdate -group dcache0 /system_tb/DUT/CPU/CM0/DCACHE/dcache_table
add wave -noupdate -group dcache0 /system_tb/DUT/CPU/CM0/DCACHE/set
add wave -noupdate -group dcache0 /system_tb/DUT/CPU/CM0/DCACHE/next_link_register
add wave -noupdate -group dcache0 /system_tb/DUT/CPU/CM0/DCACHE/link_register
add wave -noupdate -group dcache0 /system_tb/DUT/CPU/CM0/DCACHE/next_link_valid
add wave -noupdate -group dcache0 /system_tb/DUT/CPU/CM0/DCACHE/link_valid
add wave -noupdate -group dcache0 /system_tb/DUT/CPU/CM0/DCACHE/success
add wave -noupdate -group dcache0 /system_tb/DUT/CPU/DP0/dpif/datomic
add wave -noupdate -group icache0 /system_tb/DUT/CPU/CM0/ICACHE/CLK
add wave -noupdate -group icache0 /system_tb/DUT/CPU/CM0/ICACHE/nRST
add wave -noupdate -group icache0 -expand /system_tb/DUT/CPU/CM0/ICACHE/icache_table
add wave -noupdate -group icache0 /system_tb/DUT/CPU/CM0/ICACHE/tag
add wave -noupdate -group icache0 /system_tb/DUT/CPU/CM0/ICACHE/index
add wave -noupdate -group icache0 /system_tb/DUT/CPU/CM0/ICACHE/hit
add wave -noupdate -group icache0 /system_tb/DUT/CPU/CM0/ICACHE/miss
add wave -noupdate -group icache0 /system_tb/DUT/CPU/CM0/ICACHE/i
add wave -noupdate -group datapath_cache0 /system_tb/DUT/CPU/CM0/dcif/halt
add wave -noupdate -group datapath_cache0 /system_tb/DUT/CPU/CM0/dcif/ihit
add wave -noupdate -group datapath_cache0 /system_tb/DUT/CPU/CM0/dcif/imemREN
add wave -noupdate -group datapath_cache0 /system_tb/DUT/CPU/CM0/dcif/imemload
add wave -noupdate -group datapath_cache0 /system_tb/DUT/CPU/CM0/dcif/imemaddr
add wave -noupdate -group datapath_cache0 /system_tb/DUT/CPU/CM0/dcif/dhit
add wave -noupdate -group datapath_cache0 /system_tb/DUT/CPU/CM0/dcif/datomic
add wave -noupdate -group datapath_cache0 /system_tb/DUT/CPU/CM0/dcif/dmemREN
add wave -noupdate -group datapath_cache0 /system_tb/DUT/CPU/CM0/dcif/dmemWEN
add wave -noupdate -group datapath_cache0 /system_tb/DUT/CPU/CM0/dcif/flushed
add wave -noupdate -group datapath_cache0 /system_tb/DUT/CPU/CM0/dcif/dmemload
add wave -noupdate -group datapath_cache0 /system_tb/DUT/CPU/CM0/dcif/dmemstore
add wave -noupdate -group datapath_cache0 /system_tb/DUT/CPU/CM0/dcif/dmemaddr
add wave -noupdate -group ALU0 /system_tb/DUT/CPU/DP0/aluif/neg
add wave -noupdate -group ALU0 /system_tb/DUT/CPU/DP0/aluif/ovf
add wave -noupdate -group ALU0 /system_tb/DUT/CPU/DP0/aluif/zero
add wave -noupdate -group ALU0 /system_tb/DUT/CPU/DP0/aluif/ALUOP
add wave -noupdate -group ALU0 /system_tb/DUT/CPU/DP0/aluif/portA
add wave -noupdate -group ALU0 /system_tb/DUT/CPU/DP0/aluif/portB
add wave -noupdate -group ALU0 /system_tb/DUT/CPU/DP0/aluif/out_port
add wave -noupdate -group control_unit0 /system_tb/DUT/CPU/DP0/CU_DUT/opcode
add wave -noupdate -group control_unit0 /system_tb/DUT/CPU/DP0/cuif/instr
add wave -noupdate -group control_unit0 /system_tb/DUT/CPU/DP0/cuif/flush
add wave -noupdate -group control_unit0 /system_tb/DUT/CPU/DP0/cuif/stall
add wave -noupdate -group control_unit0 /system_tb/DUT/CPU/DP0/cuif/rs
add wave -noupdate -group control_unit0 /system_tb/DUT/CPU/DP0/cuif/rd
add wave -noupdate -group control_unit0 /system_tb/DUT/CPU/DP0/cuif/rt
add wave -noupdate -group control_unit0 /system_tb/DUT/CPU/DP0/cuif/imm_val
add wave -noupdate -group control_unit0 /system_tb/DUT/CPU/DP0/cuif/ALUOP
add wave -noupdate -group control_unit0 /system_tb/DUT/CPU/DP0/cuif/PCSrc
add wave -noupdate -group control_unit0 /system_tb/DUT/CPU/DP0/cuif/RegDst
add wave -noupdate -group control_unit0 /system_tb/DUT/CPU/DP0/cuif/ExtOp
add wave -noupdate -group control_unit0 /system_tb/DUT/CPU/DP0/cuif/halt
add wave -noupdate -group control_unit0 /system_tb/DUT/CPU/DP0/cuif/RegWr
add wave -noupdate -group control_unit0 /system_tb/DUT/CPU/DP0/cuif/MemtoReg
add wave -noupdate -group control_unit0 /system_tb/DUT/CPU/DP0/cuif/dWEN
add wave -noupdate -group control_unit0 /system_tb/DUT/CPU/DP0/cuif/dREN
add wave -noupdate -group control_unit0 /system_tb/DUT/CPU/DP0/cuif/iREN
add wave -noupdate -group control_unit0 /system_tb/DUT/CPU/DP0/cuif/ALUSrc
add wave -noupdate -group control_unit0 /system_tb/DUT/CPU/DP0/cuif/JAL
add wave -noupdate -group control_unit0 /system_tb/DUT/CPU/DP0/cuif/LUI
add wave -noupdate -group control_unit0 /system_tb/DUT/CPU/DP0/cuif/JR
add wave -noupdate -group control_unit0 /system_tb/DUT/CPU/DP0/cuif/BNE
add wave -noupdate -group control_unit0 /system_tb/DUT/CPU/DP0/cuif/BEQ
add wave -noupdate -group control_unit0 /system_tb/DUT/CPU/DP0/cuif/equal
add wave -noupdate -group control_unit0 /system_tb/DUT/CPU/DP0/cuif/dhit
add wave -noupdate -group control_unit0 /system_tb/DUT/CPU/DP0/cuif/ihit
add wave -noupdate -group IFID0 /system_tb/DUT/CPU/DP0/ifid/flush
add wave -noupdate -group IFID0 /system_tb/DUT/CPU/DP0/ifid/stall
add wave -noupdate -group IFID0 /system_tb/DUT/CPU/DP0/ifid/flush_branch
add wave -noupdate -group IFID0 /system_tb/DUT/CPU/DP0/ifid/ihit
add wave -noupdate -group IFID0 /system_tb/DUT/CPU/DP0/ifid/dhit
add wave -noupdate -group IFID0 /system_tb/DUT/CPU/DP0/ifid/mem_op
add wave -noupdate -group IFID0 /system_tb/DUT/CPU/DP0/ifid/pc_in
add wave -noupdate -group IFID0 /system_tb/DUT/CPU/DP0/ifid/pc_out
add wave -noupdate -group IFID0 /system_tb/DUT/CPU/DP0/ifid/npc_in
add wave -noupdate -group IFID0 /system_tb/DUT/CPU/DP0/ifid/npc_out
add wave -noupdate -group IFID0 /system_tb/DUT/CPU/DP0/ifid/instr_in
add wave -noupdate -group IFID0 /system_tb/DUT/CPU/DP0/ifid/instr_out
add wave -noupdate -group IFID0 /system_tb/DUT/CPU/DP0/ifid/opcode_in
add wave -noupdate -group IFID0 /system_tb/DUT/CPU/DP0/ifid/opcode_out
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/flush
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/stall
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/flush_branch
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/ihit
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/dhit
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/mem_op
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/pc_in
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/pc_out
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/npc_in
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/npc_out
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/instr_in
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/instr_out
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/rdat1_in
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/rdat2_in
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/rdat1_out
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/rdat2_out
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/rs_in
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/rd_in
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/rt_in
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/rs_out
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/rd_out
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/rt_out
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/imm16_in
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/imm16_out
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/imm32_in
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/imm32_out
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/halt_in
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/halt_out
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/ALUSrc_in
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/JAL_in
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/BEQ_in
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/RegWr_in
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/ALUSrc_out
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/JAL_out
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/BEQ_out
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/RegWr_out
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/BNE_in
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/BNE_out
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/PCSrc_in
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/ExtOp_in
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/RegDst_in
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/PCSrc_out
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/ExtOp_out
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/RegDst_out
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/MemtoReg_in
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/MemWr_in
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/iREN_in
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/MemtoReg_out
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/MemWr_out
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/iREN_out
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/ALUOP_in
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/ALUOP_out
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/opcode_in
add wave -noupdate -group IDEX0 /system_tb/DUT/CPU/DP0/idex/opcode_out
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/opcode_out
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/opcode_in
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/stall
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/flush
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/ihit
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/dhit
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/zero_out
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/zero_in
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/br_nottaken_in
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/br_nottaken_out
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/mem_op
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/pc_in
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/pc_out
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/npc_in
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/npc_out
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/jraddr_forward_in
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/jraddr_forward_out
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/instr_in
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/instr_out
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/ALUOut_in
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/ALUOut_out
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/rdat2_in
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/rdat2_out
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/rdat1_in
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/rdat1_out
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/rs_in
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/rd_in
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/rt_in
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/rs_out
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/rd_out
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/rt_out
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/imm16_in
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/imm16_out
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/imm32_in
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/imm32_out
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/halt_in
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/halt_out
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/ALUSrc_in
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/JAL_in
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/BEQ_in
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/RegWr_in
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/ALUSrc_out
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/JAL_out
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/BEQ_out
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/RegWr_out
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/BNE_in
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/BNE_out
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/PCSrc_in
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/ExtOp_in
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/RegDst_in
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/PCSrc_out
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/ExtOp_out
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/RegDst_out
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/MemtoReg_in
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/MemWr_in
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/iREN_in
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/MemtoReg_out
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/MemWr_out
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/iREN_out
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/ALUOP_in
add wave -noupdate -group EXMEM0 /system_tb/DUT/CPU/DP0/exmem/ALUOP_out
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/flush
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/stall
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/ihit
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/dhit
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/mem_op
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/branchaddr_out
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/branchaddr_in
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/pc_in
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/pc_out
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/npc_in
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/npc_out
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/ALUOut_in
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/ALUOut_out
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/dmemload_in
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/dmemload_out
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/instr_in
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/instr_out
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/opcode_in
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/opcode_out
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/funct_in
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/funct_out
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/rdat2_in
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/rdat2_out
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/rdat1_in
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/rdat1_out
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/rs_in
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/rd_in
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/rt_in
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/rs_out
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/rd_out
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/rt_out
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/imm32_in
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/imm32_out
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/imm16_in
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/imm16_out
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/halt_in
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/halt_out
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/ALUSrc_in
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/JAL_in
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/BEQ_in
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/RegWr_in
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/ALUSrc_out
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/JAL_out
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/BEQ_out
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/RegWr_out
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/PCSrc_in
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/ExtOp_in
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/RegDst_in
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/PCSrc_out
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/ExtOp_out
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/RegDst_out
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/MemtoReg_in
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/MemWr_in
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/iREN_in
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/MemtoReg_out
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/MemWr_out
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/iREN_out
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/ALUOP_in
add wave -noupdate -group MEMWB0 /system_tb/DUT/CPU/DP0/memwb/ALUOP_out
add wave -noupdate -group RegisterFile0 /system_tb/DUT/CPU/DP0/RF_DUT/registers
add wave -noupdate -group RegisterFile0 /system_tb/DUT/CPU/DP0/rfif/WEN
add wave -noupdate -group RegisterFile0 /system_tb/DUT/CPU/DP0/rfif/wsel
add wave -noupdate -group RegisterFile0 /system_tb/DUT/CPU/DP0/rfif/rsel1
add wave -noupdate -group RegisterFile0 /system_tb/DUT/CPU/DP0/rfif/rsel2
add wave -noupdate -group RegisterFile0 /system_tb/DUT/CPU/DP0/rfif/wdat
add wave -noupdate -group RegisterFile0 /system_tb/DUT/CPU/DP0/rfif/rdat1
add wave -noupdate -group RegisterFile0 /system_tb/DUT/CPU/DP0/rfif/rdat2
add wave -noupdate -group FUIF0 /system_tb/DUT/CPU/DP0/fuif/forwardA
add wave -noupdate -group FUIF0 /system_tb/DUT/CPU/DP0/fuif/forwardB
add wave -noupdate -group FUIF0 /system_tb/DUT/CPU/DP0/fuif/RegWr_memwb
add wave -noupdate -group FUIF0 /system_tb/DUT/CPU/DP0/fuif/RegWr_exmem
add wave -noupdate -group FUIF0 /system_tb/DUT/CPU/DP0/fuif/rs_idex
add wave -noupdate -group FUIF0 /system_tb/DUT/CPU/DP0/fuif/rt_idex
add wave -noupdate -group FUIF0 /system_tb/DUT/CPU/DP0/fuif/rt_memwb
add wave -noupdate -group FUIF0 /system_tb/DUT/CPU/DP0/fuif/rd_memwb
add wave -noupdate -group FUIF0 /system_tb/DUT/CPU/DP0/fuif/rt_exmem
add wave -noupdate -group FUIF0 /system_tb/DUT/CPU/DP0/fuif/rd_exmem
add wave -noupdate -group FUIF0 /system_tb/DUT/CPU/DP0/fuif/RegDst_memwb
add wave -noupdate -group FUIF0 /system_tb/DUT/CPU/DP0/fuif/RegDst_exmem
add wave -noupdate -group FUIF0 /system_tb/DUT/CPU/DP0/fuif/ALUOut_exmem
add wave -noupdate -group FUIF0 /system_tb/DUT/CPU/DP0/fuif/wdat_memwb
add wave -noupdate -group HUIF0 /system_tb/DUT/CPU/DP0/huif/instr
add wave -noupdate -group HUIF0 /system_tb/DUT/CPU/DP0/HU_DUT/instr_opcode
add wave -noupdate -group HUIF0 /system_tb/DUT/CPU/DP0/huif/equal_exmem
add wave -noupdate -group HUIF0 /system_tb/DUT/CPU/DP0/huif/BEQ_exmem
add wave -noupdate -group HUIF0 /system_tb/DUT/CPU/DP0/huif/BNE_exmem
add wave -noupdate -group HUIF0 /system_tb/DUT/CPU/DP0/huif/dhit
add wave -noupdate -group HUIF0 /system_tb/DUT/CPU/DP0/huif/MemtoReg_idex
add wave -noupdate -group HUIF0 /system_tb/DUT/CPU/DP0/huif/MemWr_idex
add wave -noupdate -group HUIF0 /system_tb/DUT/CPU/DP0/huif/ihit
add wave -noupdate -group HUIF0 /system_tb/DUT/CPU/DP0/huif/RegWr_exmem
add wave -noupdate -group HUIF0 /system_tb/DUT/CPU/DP0/huif/br_nottaken
add wave -noupdate -group HUIF0 /system_tb/DUT/CPU/DP0/huif/halt
add wave -noupdate -group HUIF0 /system_tb/DUT/CPU/DP0/huif/RegDst_exmem
add wave -noupdate -group HUIF0 /system_tb/DUT/CPU/DP0/huif/MemtoReg_exmem
add wave -noupdate -group HUIF0 /system_tb/DUT/CPU/DP0/huif/MemWr_exmem
add wave -noupdate -group HUIF0 /system_tb/DUT/CPU/DP0/huif/mem_op
add wave -noupdate -group HUIF0 /system_tb/DUT/CPU/DP0/huif/flush_ifid
add wave -noupdate -group HUIF0 /system_tb/DUT/CPU/DP0/huif/stall_ifid
add wave -noupdate -group HUIF0 /system_tb/DUT/CPU/DP0/huif/flush_idex
add wave -noupdate -group HUIF0 /system_tb/DUT/CPU/DP0/huif/stall_idex
add wave -noupdate -group HUIF0 /system_tb/DUT/CPU/DP0/huif/flush_exmem
add wave -noupdate -group HUIF0 /system_tb/DUT/CPU/DP0/huif/stall_exmem
add wave -noupdate -group HUIF0 /system_tb/DUT/CPU/DP0/huif/flush_memwb
add wave -noupdate -group HUIF0 /system_tb/DUT/CPU/DP0/huif/stall_memwb
add wave -noupdate -group HUIF0 /system_tb/DUT/CPU/DP0/huif/flush_branch_ifid
add wave -noupdate -group HUIF0 /system_tb/DUT/CPU/DP0/huif/flush_branch_idex
add wave -noupdate -group HUIF0 /system_tb/DUT/CPU/DP0/huif/PCSrc_exmem
add wave -noupdate -group HUIF0 /system_tb/DUT/CPU/DP0/huif/PCSrc_idex
add wave -noupdate -group HUIF0 /system_tb/DUT/CPU/DP0/huif/rt_idex
add wave -noupdate -group HUIF0 /system_tb/DUT/CPU/DP0/huif/rt_exmem
add wave -noupdate -group HUIF0 /system_tb/DUT/CPU/DP0/huif/rd_exmem
add wave -noupdate -group HUIF0 /system_tb/DUT/CPU/DP0/huif/rs_ifid
add wave -noupdate -group HUIF0 /system_tb/DUT/CPU/DP0/huif/rt_ifid
add wave -noupdate -divider CPU1
add wave -noupdate -group PC1 /system_tb/DUT/CPU/DP1/pcif/pc
add wave -noupdate -group PC1 /system_tb/DUT/CPU/DP1/pcif/next_pc
add wave -noupdate -group PC1 /system_tb/DUT/CPU/DP1/pcif/pc_comb
add wave -noupdate -group PC1 /system_tb/DUT/CPU/DP1/pcif/pc_incr
add wave -noupdate -group CIF1 /system_tb/DUT/CPU/cif1/iwait
add wave -noupdate -group CIF1 /system_tb/DUT/CPU/cif1/dwait
add wave -noupdate -group CIF1 /system_tb/DUT/CPU/cif1/iREN
add wave -noupdate -group CIF1 /system_tb/DUT/CPU/cif1/dREN
add wave -noupdate -group CIF1 /system_tb/DUT/CPU/cif1/dWEN
add wave -noupdate -group CIF1 /system_tb/DUT/CPU/cif1/iload
add wave -noupdate -group CIF1 /system_tb/DUT/CPU/cif1/dload
add wave -noupdate -group CIF1 /system_tb/DUT/CPU/cif1/dstore
add wave -noupdate -group CIF1 /system_tb/DUT/CPU/cif1/iaddr
add wave -noupdate -group CIF1 /system_tb/DUT/CPU/cif1/daddr
add wave -noupdate -group CIF1 /system_tb/DUT/CPU/cif1/ccwait
add wave -noupdate -group CIF1 /system_tb/DUT/CPU/cif1/ccinv
add wave -noupdate -group CIF1 /system_tb/DUT/CPU/cif1/ccwrite
add wave -noupdate -group CIF1 /system_tb/DUT/CPU/cif1/cctrans
add wave -noupdate -group CIF1 /system_tb/DUT/CPU/cif1/ccsnoopaddr
add wave -noupdate -group CIF1 /system_tb/DUT/CPU/cif1/ccflushed
add wave -noupdate -group dcache1 /system_tb/DUT/CPU/CM1/DCACHE/currState
add wave -noupdate -group dcache1 /system_tb/DUT/CPU/CM1/DCACHE/nextState
add wave -noupdate -group dcache1 /system_tb/DUT/CPU/CM1/DCACHE/CLK
add wave -noupdate -group dcache1 /system_tb/DUT/CPU/CM1/DCACHE/nRST
add wave -noupdate -group dcache1 /system_tb/DUT/CPU/CM1/DCACHE/addrTag
add wave -noupdate -group dcache1 /system_tb/DUT/CPU/CM1/DCACHE/snoopTag
add wave -noupdate -group dcache1 /system_tb/DUT/CPU/CM1/DCACHE/addrIndex
add wave -noupdate -group dcache1 /system_tb/DUT/CPU/CM1/DCACHE/snoopIndex
add wave -noupdate -group dcache1 /system_tb/DUT/CPU/CM1/DCACHE/index
add wave -noupdate -group dcache1 /system_tb/DUT/CPU/CM1/DCACHE/next_flush_set
add wave -noupdate -group dcache1 /system_tb/DUT/CPU/CM1/DCACHE/flush_set
add wave -noupdate -group dcache1 /system_tb/DUT/CPU/CM1/DCACHE/addrOffset
add wave -noupdate -group dcache1 /system_tb/DUT/CPU/CM1/DCACHE/snoopOffset
add wave -noupdate -group dcache1 /system_tb/DUT/CPU/CM1/DCACHE/next_flush_frame
add wave -noupdate -group dcache1 /system_tb/DUT/CPU/CM1/DCACHE/flush_frame
add wave -noupdate -group dcache1 /system_tb/DUT/CPU/CM1/DCACHE/snoopFrame
add wave -noupdate -group dcache1 /system_tb/DUT/CPU/CM1/DCACHE/nextSnoopFrame
add wave -noupdate -group dcache1 /system_tb/DUT/CPU/CM1/DCACHE/cnt
add wave -noupdate -group dcache1 /system_tb/DUT/CPU/CM1/DCACHE/next_cnt
add wave -noupdate -group dcache1 /system_tb/DUT/CPU/CM1/DCACHE/i
add wave -noupdate -group dcache1 /system_tb/DUT/CPU/CM1/DCACHE/j
add wave -noupdate -group dcache1 /system_tb/DUT/CPU/CM1/DCACHE/dcache_table
add wave -noupdate -group dcache1 /system_tb/DUT/CPU/CM1/DCACHE/set
add wave -noupdate -group dcache1 /system_tb/DUT/CPU/CM1/DCACHE/next_link_register
add wave -noupdate -group dcache1 /system_tb/DUT/CPU/CM1/DCACHE/link_register
add wave -noupdate -group dcache1 /system_tb/DUT/CPU/CM1/DCACHE/next_link_valid
add wave -noupdate -group dcache1 /system_tb/DUT/CPU/CM1/DCACHE/link_valid
add wave -noupdate -group dcache1 /system_tb/DUT/CPU/CM1/DCACHE/success
add wave -noupdate -group dcache1 /system_tb/DUT/CPU/DP1/dpif/datomic
add wave -noupdate -group icache1 /system_tb/DUT/CPU/CM1/ICACHE/CLK
add wave -noupdate -group icache1 /system_tb/DUT/CPU/CM1/ICACHE/nRST
add wave -noupdate -group icache1 /system_tb/DUT/CPU/CM1/ICACHE/icache_table
add wave -noupdate -group icache1 /system_tb/DUT/CPU/CM1/ICACHE/tag
add wave -noupdate -group icache1 /system_tb/DUT/CPU/CM1/ICACHE/index
add wave -noupdate -group icache1 /system_tb/DUT/CPU/CM1/ICACHE/hit
add wave -noupdate -group icache1 /system_tb/DUT/CPU/CM1/ICACHE/miss
add wave -noupdate -group icache1 /system_tb/DUT/CPU/CM1/ICACHE/i
add wave -noupdate -group datapath_cache1 /system_tb/DUT/CPU/CM1/dcif/halt
add wave -noupdate -group datapath_cache1 /system_tb/DUT/CPU/CM1/dcif/ihit
add wave -noupdate -group datapath_cache1 /system_tb/DUT/CPU/CM1/dcif/imemREN
add wave -noupdate -group datapath_cache1 /system_tb/DUT/CPU/CM1/dcif/imemload
add wave -noupdate -group datapath_cache1 /system_tb/DUT/CPU/CM1/dcif/imemaddr
add wave -noupdate -group datapath_cache1 /system_tb/DUT/CPU/CM1/dcif/dhit
add wave -noupdate -group datapath_cache1 /system_tb/DUT/CPU/CM1/dcif/datomic
add wave -noupdate -group datapath_cache1 /system_tb/DUT/CPU/CM1/dcif/dmemREN
add wave -noupdate -group datapath_cache1 /system_tb/DUT/CPU/CM1/dcif/dmemWEN
add wave -noupdate -group datapath_cache1 /system_tb/DUT/CPU/CM1/dcif/flushed
add wave -noupdate -group datapath_cache1 /system_tb/DUT/CPU/CM1/dcif/dmemload
add wave -noupdate -group datapath_cache1 /system_tb/DUT/CPU/CM1/dcif/dmemstore
add wave -noupdate -group datapath_cache1 /system_tb/DUT/CPU/CM1/dcif/dmemaddr
add wave -noupdate -group ALU1 /system_tb/DUT/CPU/DP1/aluif/neg
add wave -noupdate -group ALU1 /system_tb/DUT/CPU/DP1/aluif/ovf
add wave -noupdate -group ALU1 /system_tb/DUT/CPU/DP1/aluif/zero
add wave -noupdate -group ALU1 /system_tb/DUT/CPU/DP1/aluif/ALUOP
add wave -noupdate -group ALU1 /system_tb/DUT/CPU/DP1/aluif/portA
add wave -noupdate -group ALU1 /system_tb/DUT/CPU/DP1/aluif/portB
add wave -noupdate -group ALU1 /system_tb/DUT/CPU/DP1/aluif/out_port
add wave -noupdate -group control_unit1 /system_tb/DUT/CPU/DP1/cuif/instr
add wave -noupdate -group control_unit1 /system_tb/DUT/CPU/DP1/CU_DUT/opcode
add wave -noupdate -group control_unit1 /system_tb/DUT/CPU/DP1/cuif/flush
add wave -noupdate -group control_unit1 /system_tb/DUT/CPU/DP1/cuif/stall
add wave -noupdate -group control_unit1 /system_tb/DUT/CPU/DP1/cuif/rs
add wave -noupdate -group control_unit1 /system_tb/DUT/CPU/DP1/cuif/rd
add wave -noupdate -group control_unit1 /system_tb/DUT/CPU/DP1/cuif/rt
add wave -noupdate -group control_unit1 /system_tb/DUT/CPU/DP1/cuif/imm_val
add wave -noupdate -group control_unit1 /system_tb/DUT/CPU/DP1/cuif/ALUOP
add wave -noupdate -group control_unit1 /system_tb/DUT/CPU/DP1/cuif/PCSrc
add wave -noupdate -group control_unit1 /system_tb/DUT/CPU/DP1/cuif/RegDst
add wave -noupdate -group control_unit1 /system_tb/DUT/CPU/DP1/cuif/ExtOp
add wave -noupdate -group control_unit1 /system_tb/DUT/CPU/DP1/cuif/halt
add wave -noupdate -group control_unit1 /system_tb/DUT/CPU/DP1/cuif/RegWr
add wave -noupdate -group control_unit1 /system_tb/DUT/CPU/DP1/cuif/MemtoReg
add wave -noupdate -group control_unit1 /system_tb/DUT/CPU/DP1/cuif/dWEN
add wave -noupdate -group control_unit1 /system_tb/DUT/CPU/DP1/cuif/dREN
add wave -noupdate -group control_unit1 /system_tb/DUT/CPU/DP1/cuif/iREN
add wave -noupdate -group control_unit1 /system_tb/DUT/CPU/DP1/cuif/ALUSrc
add wave -noupdate -group control_unit1 /system_tb/DUT/CPU/DP1/cuif/JAL
add wave -noupdate -group control_unit1 /system_tb/DUT/CPU/DP1/cuif/LUI
add wave -noupdate -group control_unit1 /system_tb/DUT/CPU/DP1/cuif/JR
add wave -noupdate -group control_unit1 /system_tb/DUT/CPU/DP1/cuif/BNE
add wave -noupdate -group control_unit1 /system_tb/DUT/CPU/DP1/cuif/BEQ
add wave -noupdate -group control_unit1 /system_tb/DUT/CPU/DP1/cuif/equal
add wave -noupdate -group control_unit1 /system_tb/DUT/CPU/DP1/cuif/dhit
add wave -noupdate -group control_unit1 /system_tb/DUT/CPU/DP1/cuif/ihit
add wave -noupdate -group IFID1 /system_tb/DUT/CPU/DP1/ifid/flush
add wave -noupdate -group IFID1 /system_tb/DUT/CPU/DP1/ifid/stall
add wave -noupdate -group IFID1 /system_tb/DUT/CPU/DP1/ifid/flush_branch
add wave -noupdate -group IFID1 /system_tb/DUT/CPU/DP1/ifid/ihit
add wave -noupdate -group IFID1 /system_tb/DUT/CPU/DP1/ifid/dhit
add wave -noupdate -group IFID1 /system_tb/DUT/CPU/DP1/ifid/mem_op
add wave -noupdate -group IFID1 /system_tb/DUT/CPU/DP1/ifid/pc_in
add wave -noupdate -group IFID1 /system_tb/DUT/CPU/DP1/ifid/pc_out
add wave -noupdate -group IFID1 /system_tb/DUT/CPU/DP1/ifid/npc_in
add wave -noupdate -group IFID1 /system_tb/DUT/CPU/DP1/ifid/npc_out
add wave -noupdate -group IFID1 /system_tb/DUT/CPU/DP1/ifid/instr_in
add wave -noupdate -group IFID1 /system_tb/DUT/CPU/DP1/ifid/instr_out
add wave -noupdate -group IFID1 /system_tb/DUT/CPU/DP1/ifid/opcode_in
add wave -noupdate -group IFID1 /system_tb/DUT/CPU/DP1/ifid/opcode_out
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/opcode_out
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/opcode_in
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/flush
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/stall
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/flush_branch
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/ihit
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/dhit
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/mem_op
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/pc_in
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/pc_out
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/npc_in
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/npc_out
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/instr_in
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/instr_out
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/rdat1_in
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/rdat2_in
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/rdat1_out
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/rdat2_out
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/rs_in
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/rd_in
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/rt_in
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/rs_out
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/rd_out
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/rt_out
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/imm16_in
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/imm16_out
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/imm32_in
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/imm32_out
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/halt_in
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/halt_out
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/ALUSrc_in
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/JAL_in
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/BEQ_in
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/RegWr_in
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/ALUSrc_out
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/JAL_out
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/BEQ_out
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/RegWr_out
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/BNE_in
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/BNE_out
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/PCSrc_in
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/ExtOp_in
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/RegDst_in
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/PCSrc_out
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/ExtOp_out
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/RegDst_out
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/MemtoReg_in
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/MemWr_in
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/iREN_in
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/MemtoReg_out
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/MemWr_out
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/iREN_out
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/ALUOP_in
add wave -noupdate -group IDEX1 /system_tb/DUT/CPU/DP1/idex/ALUOP_out
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/opcode_out
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/opcode_in
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/stall
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/flush
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/ihit
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/dhit
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/zero_out
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/zero_in
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/br_nottaken_in
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/br_nottaken_out
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/mem_op
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/pc_in
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/pc_out
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/npc_in
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/npc_out
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/jraddr_forward_in
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/jraddr_forward_out
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/instr_in
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/instr_out
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/ALUOut_in
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/ALUOut_out
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/rdat2_in
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/rdat2_out
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/rdat1_in
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/rdat1_out
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/rs_in
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/rd_in
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/rt_in
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/rs_out
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/rd_out
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/rt_out
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/imm16_in
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/imm16_out
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/imm32_in
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/imm32_out
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/halt_in
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/halt_out
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/ALUSrc_in
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/JAL_in
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/BEQ_in
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/RegWr_in
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/ALUSrc_out
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/JAL_out
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/BEQ_out
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/RegWr_out
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/BNE_in
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/BNE_out
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/PCSrc_in
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/ExtOp_in
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/RegDst_in
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/PCSrc_out
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/ExtOp_out
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/RegDst_out
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/MemtoReg_in
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/MemWr_in
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/iREN_in
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/MemtoReg_out
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/MemWr_out
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/iREN_out
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/ALUOP_in
add wave -noupdate -group EXMEM1 /system_tb/DUT/CPU/DP1/exmem/ALUOP_out
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/flush
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/stall
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/ihit
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/dhit
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/mem_op
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/branchaddr_out
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/branchaddr_in
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/pc_in
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/pc_out
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/npc_in
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/npc_out
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/ALUOut_in
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/ALUOut_out
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/dmemload_in
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/dmemload_out
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/instr_in
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/instr_out
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/opcode_in
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/opcode_out
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/funct_in
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/funct_out
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/rdat2_in
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/rdat2_out
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/rdat1_in
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/rdat1_out
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/rs_in
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/rd_in
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/rt_in
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/rs_out
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/rd_out
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/rt_out
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/imm32_in
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/imm32_out
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/imm16_in
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/imm16_out
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/halt_in
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/halt_out
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/ALUSrc_in
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/JAL_in
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/BEQ_in
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/RegWr_in
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/ALUSrc_out
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/JAL_out
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/BEQ_out
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/RegWr_out
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/PCSrc_in
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/ExtOp_in
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/RegDst_in
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/PCSrc_out
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/ExtOp_out
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/RegDst_out
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/MemtoReg_in
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/MemWr_in
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/iREN_in
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/MemtoReg_out
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/MemWr_out
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/iREN_out
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/ALUOP_in
add wave -noupdate -group MEMWB1 /system_tb/DUT/CPU/DP1/memwb/ALUOP_out
add wave -noupdate -group RegisterFile1 /system_tb/DUT/CPU/DP1/RF_DUT/registers
add wave -noupdate -group RegisterFile1 /system_tb/DUT/CPU/DP1/rfif/WEN
add wave -noupdate -group RegisterFile1 /system_tb/DUT/CPU/DP1/rfif/wsel
add wave -noupdate -group RegisterFile1 /system_tb/DUT/CPU/DP1/rfif/rsel1
add wave -noupdate -group RegisterFile1 /system_tb/DUT/CPU/DP1/rfif/rsel2
add wave -noupdate -group RegisterFile1 /system_tb/DUT/CPU/DP1/rfif/wdat
add wave -noupdate -group RegisterFile1 /system_tb/DUT/CPU/DP1/rfif/rdat1
add wave -noupdate -group RegisterFile1 /system_tb/DUT/CPU/DP1/rfif/rdat2
add wave -noupdate -group FUIF1 /system_tb/DUT/CPU/DP1/fuif/forwardA
add wave -noupdate -group FUIF1 /system_tb/DUT/CPU/DP1/fuif/forwardB
add wave -noupdate -group FUIF1 /system_tb/DUT/CPU/DP1/fuif/RegWr_memwb
add wave -noupdate -group FUIF1 /system_tb/DUT/CPU/DP1/fuif/RegWr_exmem
add wave -noupdate -group FUIF1 /system_tb/DUT/CPU/DP1/fuif/rs_idex
add wave -noupdate -group FUIF1 /system_tb/DUT/CPU/DP1/fuif/rt_idex
add wave -noupdate -group FUIF1 /system_tb/DUT/CPU/DP1/fuif/rt_memwb
add wave -noupdate -group FUIF1 /system_tb/DUT/CPU/DP1/fuif/rd_memwb
add wave -noupdate -group FUIF1 /system_tb/DUT/CPU/DP1/fuif/rt_exmem
add wave -noupdate -group FUIF1 /system_tb/DUT/CPU/DP1/fuif/rd_exmem
add wave -noupdate -group FUIF1 /system_tb/DUT/CPU/DP1/fuif/RegDst_memwb
add wave -noupdate -group FUIF1 /system_tb/DUT/CPU/DP1/fuif/RegDst_exmem
add wave -noupdate -group FUIF1 /system_tb/DUT/CPU/DP1/fuif/ALUOut_exmem
add wave -noupdate -group FUIF1 /system_tb/DUT/CPU/DP1/fuif/wdat_memwb
add wave -noupdate -group HUIF1 /system_tb/DUT/CPU/DP1/huif/equal_exmem
add wave -noupdate -group HUIF1 /system_tb/DUT/CPU/DP1/huif/BEQ_exmem
add wave -noupdate -group HUIF1 /system_tb/DUT/CPU/DP1/huif/BNE_exmem
add wave -noupdate -group HUIF1 /system_tb/DUT/CPU/DP1/huif/dhit
add wave -noupdate -group HUIF1 /system_tb/DUT/CPU/DP1/huif/MemtoReg_idex
add wave -noupdate -group HUIF1 /system_tb/DUT/CPU/DP1/huif/MemWr_idex
add wave -noupdate -group HUIF1 /system_tb/DUT/CPU/DP1/huif/ihit
add wave -noupdate -group HUIF1 /system_tb/DUT/CPU/DP1/huif/RegWr_exmem
add wave -noupdate -group HUIF1 /system_tb/DUT/CPU/DP1/huif/br_nottaken
add wave -noupdate -group HUIF1 /system_tb/DUT/CPU/DP1/huif/halt
add wave -noupdate -group HUIF1 /system_tb/DUT/CPU/DP1/huif/RegDst_exmem
add wave -noupdate -group HUIF1 /system_tb/DUT/CPU/DP1/huif/MemtoReg_exmem
add wave -noupdate -group HUIF1 /system_tb/DUT/CPU/DP1/huif/MemWr_exmem
add wave -noupdate -group HUIF1 /system_tb/DUT/CPU/DP1/huif/mem_op
add wave -noupdate -group HUIF1 /system_tb/DUT/CPU/DP1/huif/flush_ifid
add wave -noupdate -group HUIF1 /system_tb/DUT/CPU/DP1/huif/stall_ifid
add wave -noupdate -group HUIF1 /system_tb/DUT/CPU/DP1/huif/flush_idex
add wave -noupdate -group HUIF1 /system_tb/DUT/CPU/DP1/huif/stall_idex
add wave -noupdate -group HUIF1 /system_tb/DUT/CPU/DP1/huif/flush_exmem
add wave -noupdate -group HUIF1 /system_tb/DUT/CPU/DP1/huif/stall_exmem
add wave -noupdate -group HUIF1 /system_tb/DUT/CPU/DP1/huif/flush_memwb
add wave -noupdate -group HUIF1 /system_tb/DUT/CPU/DP1/huif/stall_memwb
add wave -noupdate -group HUIF1 /system_tb/DUT/CPU/DP1/huif/flush_branch_ifid
add wave -noupdate -group HUIF1 /system_tb/DUT/CPU/DP1/huif/flush_branch_idex
add wave -noupdate -group HUIF1 /system_tb/DUT/CPU/DP1/huif/PCSrc_exmem
add wave -noupdate -group HUIF1 /system_tb/DUT/CPU/DP1/huif/PCSrc_idex
add wave -noupdate -group HUIF1 /system_tb/DUT/CPU/DP1/huif/rt_idex
add wave -noupdate -group HUIF1 /system_tb/DUT/CPU/DP1/huif/rt_exmem
add wave -noupdate -group HUIF1 /system_tb/DUT/CPU/DP1/huif/rd_exmem
add wave -noupdate -group HUIF1 /system_tb/DUT/CPU/DP1/huif/rs_ifid
add wave -noupdate -group HUIF1 /system_tb/DUT/CPU/DP1/huif/rt_ifid
add wave -noupdate -group HUIF1 /system_tb/DUT/CPU/DP1/huif/instr
add wave -noupdate -divider BUS
add wave -noupdate -group {BUS Controller} /system_tb/DUT/CPU/CC/state
add wave -noupdate -group {BUS Controller} /system_tb/DUT/CPU/CC/next_state
add wave -noupdate -group {BUS Controller} /system_tb/DUT/CPU/CC/ccif/iwait
add wave -noupdate -group {BUS Controller} /system_tb/DUT/CPU/CC/ccif/dwait
add wave -noupdate -group {BUS Controller} /system_tb/DUT/CPU/CC/ccif/iREN
add wave -noupdate -group {BUS Controller} /system_tb/DUT/CPU/CC/ccif/dREN
add wave -noupdate -group {BUS Controller} /system_tb/DUT/CPU/CC/ccif/dWEN
add wave -noupdate -group {BUS Controller} /system_tb/DUT/CPU/CC/ccif/iload
add wave -noupdate -group {BUS Controller} /system_tb/DUT/CPU/CC/ccif/dload
add wave -noupdate -group {BUS Controller} /system_tb/DUT/CPU/CC/ccif/dstore
add wave -noupdate -group {BUS Controller} /system_tb/DUT/CPU/CC/ccif/iaddr
add wave -noupdate -group {BUS Controller} /system_tb/DUT/CPU/CC/ccif/daddr
add wave -noupdate -group {BUS Controller} /system_tb/DUT/CPU/CC/ccif/ccwait
add wave -noupdate -group {BUS Controller} /system_tb/DUT/CPU/CC/ccif/ccinv
add wave -noupdate -group {BUS Controller} /system_tb/DUT/CPU/CC/ccif/ccwrite
add wave -noupdate -group {BUS Controller} /system_tb/DUT/CPU/CC/ccif/cctrans
add wave -noupdate -group {BUS Controller} /system_tb/DUT/CPU/CC/ccif/ccsnoopaddr
add wave -noupdate -group {BUS Controller} /system_tb/DUT/CPU/CC/ccif/ramWEN
add wave -noupdate -group {BUS Controller} /system_tb/DUT/CPU/CC/ccif/ramREN
add wave -noupdate -group {BUS Controller} /system_tb/DUT/CPU/CC/ccif/ramstate
add wave -noupdate -group {BUS Controller} /system_tb/DUT/CPU/CC/ccif/ramaddr
add wave -noupdate -group {BUS Controller} /system_tb/DUT/CPU/CC/ccif/ramstore
add wave -noupdate -group {BUS Controller} /system_tb/DUT/CPU/CC/ccif/ramload
add wave -noupdate -group {BUS Controller} /system_tb/DUT/CPU/CC/next_snooper
add wave -noupdate -group {BUS Controller} /system_tb/DUT/CPU/CC/next_snoopy
add wave -noupdate -group {BUS Controller} /system_tb/DUT/CPU/CC/nRST
add wave -noupdate -group {BUS Controller} /system_tb/DUT/CPU/CC/snooper
add wave -noupdate -group {BUS Controller} /system_tb/DUT/CPU/CC/snoopy
add wave -noupdate -group {BUS Controller} /system_tb/DUT/CPU/CC/ireq
add wave -noupdate -group {BUS Controller} /system_tb/DUT/CPU/CC/next_ireq
add wave -noupdate -group {BUS Controller} /system_tb/DUT/CPU/CC/dreq
add wave -noupdate -group {BUS Controller} /system_tb/DUT/CPU/CC/next_dreq
add wave -noupdate -divider RAM
add wave -noupdate -group RAM /system_tb/DUT/RAM/ramif/ramREN
add wave -noupdate -group RAM /system_tb/DUT/RAM/ramif/ramWEN
add wave -noupdate -group RAM /system_tb/DUT/RAM/ramif/ramaddr
add wave -noupdate -group RAM /system_tb/DUT/RAM/ramif/ramstore
add wave -noupdate -group RAM /system_tb/DUT/RAM/ramif/ramload
add wave -noupdate -group RAM /system_tb/DUT/RAM/ramif/ramstate
add wave -noupdate -group RAM /system_tb/DUT/RAM/ramif/memREN
add wave -noupdate -group RAM /system_tb/DUT/RAM/ramif/memWEN
add wave -noupdate -group RAM /system_tb/DUT/RAM/ramif/memaddr
add wave -noupdate -group RAM /system_tb/DUT/RAM/ramif/memstore
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {2813309 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 168
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {601020 ps} {3005100 ps}
